### ISSUE TITLE
Can not be able to show config

### ISSUE THREAD

**Issue by shahryarjb** [hrostami/aio-proxy#2]
I attempted to install Hysteria V2 and Tuic, but the installation process never finished, and I was unable to view the configuration options.

![Screenshot 2023-10-01 at 01 59 14](https://github.com/hrostami/aio-proxy/assets/8413604/fe5c52f5-62f9-45f0-9427-56b0b601a419)

You will be able to view the error if you choose to run it manually; the x-ui panel is installed on my server.

**Comment by shahryarjb** [comment]
Hello, I am using `Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-84-generic x86_64)`

It did not work to re-installing hysteria v2 and tuic, I think it can be installed even.
no way to see the log?

By the way when I want to show used port I get this error:

```
Ports in use and their corresponding processes:
----------------------------------------------
/dev/fd/63: line 1448: column: command not found
```

**Comment by hrostami** [comment]
I added net-tools installation which should fix the problem with not showing the ports in use. try again and check if the ports that you've set for hysteria2 and tuic are being used by anything other than those.

**Comment by shahryarjb** [comment]
Thanks, I think it is fixed, because I can see the configs and full install the h2 and tuic

**Comment by shahryarjb** [comment]
I have a question, how can use hysteria v2 for multi user for example 4 user? because it creates one user and each user connect the other can not be able to use
