### ISSUE TITLE
Hiddify Reality Scanner

### ISSUE THREAD

**Issue by p19lord** [hrostami/aio-proxy#4]
Hi
Initially, I'd like to personally thank you for this great script and also mention that I received an error while I was using Hiddify Reality Scanner the error is as follows:

```
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)
A unified platform for anti-censorship.
2023/11/28 23:33:18 [Info] infra/conf/serial: Reading config: server_config.json
Failed to start: main: failed to load config files: [server_config.json] > infra/conf: Failed to build REALITY config. > infra/conf: empty "serverNames"
```

I'd appreciate it if you could help me.
Thanks

**Comment by hrostami** [comment]
Hey there, you're very welcome. 
Did you run the script as root user?
